config/routes.rb
Rails.application.routes.draw do
  mount Motor::Admin => '/super_admin'

  devise_for :users, controllers: {
    omniauth_callbacks: 'users/omniauth_callbacks'
  }

  root "home#index"

  # resources :articles

  namespace :blog do
    resources :articles
  end

  resource :user, only: %i[edit update destroy]
  resources :users, only: %i[index show]

  get "/pages/:page" => "pages#show", as: :page

  match '/404', to: 'errors#not_found', via: :all
  match '/422', to: 'errors#internal_server_error', via: :all
  match '/500', to: 'errors#internal_server_error', via: :all
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  include Pagy::Backend

  rescue_from CanCan::AccessDenied do |exception|
    redirect_to request.referer || root_path, alert: exception.message
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  include Pagy::Frontend
  include Heroicon::Engine.helpers

  def page_title
    "Rails + Ralix + Tailwind | #{controller_name.humanize}"
  end

  def body_class
    "#{controller_name}-#{action_name}"
  end

  def nav_link_class(section, extra = nil)
    if section == controller_name
      "bg-gray-900 text-white px-3 py-2 rounded-md text-sm font-medium #{extra}"
    else
      "text-gray-300 hover:bg-gray-700 hover:text-white px-3 py-2 rounded-md text-sm font-medium #{extra}"
    end
  end

  def time_ago(time_object)
    "#{time_ago_in_words(time_object)} ago"
  end

  def format_time(time_object)
    l(time_object, format: :long)
  end
end

app/views/application/_error_messages.html.erb
<% if object.errors.any? %>
  <div class="my-4 p-4 bg-red-600 text-white rounded">
    <b class="text-xl"><%= pluralize(object.errors.count, "error") %> found:</b>

    <ul class="list-none">
      <% object.errors.each do |error| %>
        <li><%= error.full_message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/application/_flash_messages.html.erb
<% flash.each do |key, msg| %>
  <div class="flex items-center justify-between px-8 py-4 bg-amber-100">
    <%= msg %>
    <button onclick="closeFlashAlert()"><%= heroicon "x-mark" %></button>
  </div>
<% end %>

app/views/application/_footer.html.erb
<footer class="mx-auto mt-16 w-full max-w-container px-4 sm:px-6 lg:px-8">
  <div class="border-t border-slate-900/5 py-5">
    <p class="mt-4 text-center text-sm leading-6 text-slate-500">© <%= Time.now.year %> Ralix Core Team. All rights reserved.</p>
    <div class="mt-4 flex items-center justify-center space-x-4 text-sm font-semibold leading-6">
      <%= link_to "About us", page_path(:about) %>
      <div class="h-4 w-px bg-slate-500/20"></div>
      <%= link_to "Terms", page_path(:terms) %>
      <div class="h-4 w-px bg-slate-500/20"></div>
      <%= link_to "Privacy policy", page_path(:privacy_policy) %>
    </div>
  </div>
</footer>

app/views/application/_header.html.erb
<nav class="bg-gray-800">
  <div class="mx-auto px-6 md:px-12">
    <div class="flex h-16 items-center justify-between">
      <div class="flex items-center">
        <div class="flex-shrink-0">
          <a href="<%= root_path %>" class="text-white text-2xl">Starter Kit</a>
        </div>
        <div class="hidden sm:block">
          <div class="ml-8 flex items-baseline space-x-4">
            <a href="<%= root_path %>" class="<%= nav_link_class("home") %>">Home</a>
            <a href="<%= blog_articles_path %>" class="<%= nav_link_class("articles") %>">Blog</a>
            <a href="<%= users_path %>" class="<%= nav_link_class("users") %>">Users</a>
          </div>
        </div>
      </div>
      <div class="hidden sm:block">
        <div class="ml-4 flex items-center md:ml-6">
          <div class="relative ml-3">
            <% if user_signed_in? %>
              <a href="<%= edit_user_path %>" class="flex max-w-xs items-center rounded-full bg-gray-800 text-sm">
                <%= avatar(current_user) %>
              </a>
            <% else %>
              <%= link_to "Sign in", new_user_session_path, class: "text-gray-300 hover:bg-gray-700 hover:text-white px-3 py-2 rounded-md text-sm font-medium" %>
            <% end %>
          </div>
        </div>
      </div>
      <div class="sm:hidden">
        <button class="<%= nav_link_class(nil) %>" onclick="toggleMenu()">
          <%= heroicon "bars-3" %>
        </button>
      </div>
    </div>
  </div>

  <div class="sm:hidden hidden mobile-menu">
    <div class="space-y-2 px-2 pb-3 sm:px-3">
      <a href="<%= root_path %>" class="<%= nav_link_class("home", "block") %>">Home</a>
      <a href="<%= blog_articles_path %>" class="<%= nav_link_class("articles.bak", "block") %>">Blog</a>
      <a href="<%= users_path %>" class="<%= nav_link_class("users", "block") %>">Users</a>
      <% unless user_signed_in? %>
        <a href="<%= new_user_session_path %>" class="<%= nav_link_class(nil, "block") %>">Sign in</a>
      <% end %>
    </div>
    <% if user_signed_in? %>
      <div class="border-t border-gray-700 py-4">
        <a href="<%= edit_user_path %>">
          <div class="flex items-center px-5">
            <div class="flex-shrink-0">
              <%= avatar(current_user) %>
            </div>
            <div class="ml-3">
              <div class="text-base font-medium leading-none text-white"><%= current_user.name %></div>
              <div class="text-sm font-medium leading-none text-gray-400"><%= current_user.email %></div>
            </div>
          </div>
        </a>
      </div>
    <% end %>
  </div>
</nav>

app/views/application/_remote_modal.html.erb
<div class="modal" id="remote-modal" aria-hidden="true">
  <div class="modal-overlay" tabindex="-1" data-micromodal-close>
    <div class="modal-container" role="dialog">
      <header class="flex items-center justify-between">
        <h1 class="modal-title"></h1>
        <button class="outline-none" data-micromodal-close>
          <%= heroicon "x-mark", options: { class: "w-8 h-8" } %>
        </button>
      </header>
      <main class="my-2">
        <p>Loading ...</p>
      </main>
    </div>
  </div>
</div>