config/routes.rb
Rails.application.routes.draw do
  mount Motor::Admin => '/super_admin'

  devise_for :users, controllers: {
    omniauth_callbacks: 'users/omniauth_callbacks'
  }

  root "home#index"

  # resources :articles

  namespace :blog do
    resources :articles
  end

  resource :user, only: %i[edit update destroy]
  resources :users, only: %i[index show]

  get "/pages/:page" => "pages#show", as: :page

  match '/404', to: 'errors#not_found', via: :all
  match '/422', to: 'errors#internal_server_error', via: :all
  match '/500', to: 'errors#internal_server_error', via: :all
end

app/models/article.rb
# == Schema Information
#
# Table name: articles
#
#  id         :bigint           not null, primary key
#  body       :text
#  slug       :string
#  title      :string
#  uuid       :string
#  created_at :datetime         not null
#  updated_at :datetime         not null
#  user_id    :integer
#
# Indexes
#
#  index_articles_on_user_id  (user_id)
#
class Article < ApplicationRecord
  extend FriendlyId
  belongs_to :user

  before_save :generate_uuid, if: -> { uuid.nil? }    # Generate a random UUID for the uuid field

  has_rich_text :body
  friendly_id :generate_slug, use: :slugged

  validates :title, :body, presence: true
  validates :title, length: { minimum: 5 }

  def self.ransackable_attributes(auth_object = nil)
    %w[body created_at id title updated_at user_id]
  end

  def self.ransackable_associations(auth_object = nil)
    %w(rich_text_body user)
  end

  # Generate a random ID for the slug
  def generate_slug
    "#{title} #{uuid}"
  end

  def should_generate_new_friendly_id?
    title_changed? || uuid_changed? || super
  end

  def generate_uuid
    self.uuid = SecureRandom.hex(5)
  end
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  before_action :authenticate_user!, only: %i[new create edit update destroy]
  before_action :set_article, only: %i[show edit update destroy]

  authorize_resource

  def index
    @q = Article.ransack(params[:q])
    @pagy, @articles = pagy(@q.result.order(created_at: :desc), items: 4)
  end

  def show
  end

  def new
    @article = Article.new
  end

  def edit
  end

  def create
    @article = Article.new(article_params.merge(user: current_user))

    if @article.save
      redirect_to @article, notice: "Article was successfully created."
    else
      render :new, status: :unprocessable_entity
    end
  end

  def update
    if @article.update(article_params)
      redirect_to @article, notice: "Article was successfully updated."
    else
      render :edit, status: :unprocessable_entity
    end
  end

  def destroy
    @article.destroy

    redirect_to articles_url, notice: "Article was successfully destroyed."
  end

  private

  def set_article
    @article = Article.friendly.find(params[:id])
  end

  def article_params
    params.require(:article).permit(:title, :body)
  end
end

app/controllers/blog/articles_controller.rb
class Blog::ArticlesController < ApplicationController
  before_action :authenticate_user!, only: %i[new create edit update destroy]
  before_action :set_article, only: %i[show edit update destroy]

  authorize_resource

  def index
    @q = Article.ransack(params[:q])
    @pagy, @articles = pagy(@q.result.order(created_at: :desc), items: 4)
  end

  def show
    @article = Article.friendly.find(params[:id])
  end

  def new
    @article = Article.new
  end

  def edit
  end

  def create
    @article = Article.new(article_params.merge(user: current_user))

    if @article.save
      redirect_to @article, notice: "Article was successfully created."
    else
      render :new, status: :unprocessable_entity
    end
  end

  def update
    if @article.update(article_params)
      redirect_to [:blog, @article], notice: "Article was successfully updated."
    else
      render :edit, status: :unprocessable_entity
    end
  end

  def destroy
    @article.destroy

    redirect_to blog_articles_url, notice: "Article was successfully destroyed."
  end

  private

  def set_article
    @article = Article.friendly.find(params[:id])
  end

  def article_params
    params.require(:article).permit(:title, :body)
  end
end

app/helpers/articles_helper.rb
module ArticlesHelper
  def author_and_date(article)
    "by #{article.user.name} | #{format_time(article.created_at.to_date)}"
  end
end

app/helpers/blog/articles_helper.rb
module Blog::ArticlesHelper
end

app/views/blog/articles/_form.html.erb
<%= form_with(model: [:blog, article]) do |form| %>
  <%= render "application/error_messages", object: article %>

  <div>
    <%= form.label :title %>
    <%= form.text_field :title %>
  </div>

  <div>
    <%= form.label :body %>
    <%= form.rich_text_area :body %>
  </div>

  <div class="mt-4">
    <%= form.submit nil, class: 'btn' %>
  </div>
<% end %>

app/views/blog/articles/edit.html.erb
<h1>Editing article</h1>

<%= render "form", article: @article %>

<div class="mt-8">
  <p>Be careful! This action is irreversible.</p>
  <%= button_to "Destroy", [:blog, @article], method: :delete, class: "btn btn-danger" %>
</div>

app/views/blog/articles/index.html.erb
<div class="flex items-center justify-between">
  <h1>Articles</h1>
  <%= link_to new_blog_article_path, class: 'btn' do %>
    <%= heroicon "plus" %>
    New article
  <% end %>
</div>

<%= search_form_for [:blog, @q], data: { turbo_frame: "search" } do |f| %>
  <div class="relative">
    <div class="flex absolute inset-y-0 left-0 items-center pl-3 pointer-events-none">
      <%= heroicon "magnifying-glass" %>
    </div>
    <%= f.text_field :title_or_body_cont, class: "search-input p-3 pl-10 text-sm", onkeyup: "search()", placeholder: "Search ..." %>
  </div>
<% end %>

<%= turbo_frame_tag "search", target: "_top" do %>
  <div class="mt-8 grid sm:grid-cols-2 gap-8">
    <% @articles.each do |article| %>
      <article class="card">
        <h3 class="card-title">
          <%= link_to article.title, [:blog, article] %>
        </h3>
        <p class="card-subtitle">
          <%= author_and_date(article) %>
        </p>
        <div class="card-body">
          <%= truncate strip_tags(article.body.to_s), length: 160 %>
        </div>
        <div class="card-actions">
          <%= link_to 'Read more', blog_article_path(article), class: 'btn btn-outline' %>
        </div>
      </article>
    <% end %>
  </div>

  <div class="text-center mt-10">
    <%== pagy_nav(@pagy) %>
  </div>
<% end %>

app/views/blog/articles/new.html.erb
<h1>New article</h1>

<%= render "form", article: @article %>

app/views/blog/articles/show.html.erb
<div class="card my-4">
  <h1 class="card-title"><%= @article.title %></h1>

  <p class="card-subtitle">
    <%= author_and_date(@article) %>
  </p>

  <div class="card-body">
    <%= @article.body %>
  </div>

  <div class="card-actions">
    <%= link_to "Edit", edit_blog_article_path(@article), class: 'btn' %>
  </div>
</div>